// This Macro restore Layouts and OCs xml files. 
// it is usually used as a "Run Macro on Events" at startup or end of NIS

// the follwing commands have to point the saved layouts and OCs xmls (instead of xxxx)
// reload Layouts and OCs
RestoreLayoutsEx(« C:\Nikon Service\xxx », 1);
RestoreOptConfEx(« C:\Nikon Service\xxx », 1);

// Emptying ND Acquisition
ND_ResetLambdaExp();
ND_ResetMultipointExp();
ND_ResetTimeExp();
ND_ResetZSeriesExp();
